// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: trial

#ifndef _TRIAL_UI_H
#define _TRIAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_description2;
extern lv_obj_t * ui_title2;
extern lv_obj_t * ui_description1;
extern lv_obj_t * ui_title1;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_hum;
extern lv_obj_t * ui_vis;
extern lv_obj_t * ui_temp1;
extern lv_obj_t * ui_wind;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_description3;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_temp2;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_humidity1;
extern lv_obj_t * ui_windspeed;
extern lv_obj_t * ui_windspeed1;
extern lv_obj_t * ui_visibility;
extern lv_obj_t * ui_visibility1;
extern lv_obj_t * ui_Bar4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/humidity.png
LV_IMG_DECLARE(ui_img_visiblity_png);    // assets/visiblity.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_wind_png);    // assets/wind.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font14);
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_Font60);
LV_FONT_DECLARE(ui_font_opensans18);
LV_FONT_DECLARE(ui_font_opensans181);
LV_FONT_DECLARE(ui_font_opensans182);
LV_FONT_DECLARE(ui_font_opensans20);
LV_FONT_DECLARE(ui_font_opensansItalic);
LV_FONT_DECLARE(ui_font_opensansItalic1);
LV_FONT_DECLARE(ui_font_opensansItalic2);
LV_FONT_DECLARE(ui_font_opensansSemiBolt20);
LV_FONT_DECLARE(ui_font_opensansSemiBolt21);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
