// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: trial

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 792);
    lv_obj_set_height(ui_Panel1, 317);
    lv_obj_set_x(ui_Panel1, 238);
    lv_obj_set_y(ui_Panel1, 0);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_description2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_description2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_description2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_description2, 410);
    lv_obj_set_y(ui_description2, 270);
    lv_label_set_long_mode(ui_description2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_description2, "line2");
    lv_obj_set_style_text_font(ui_description2, &ui_font_opensans182, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_description2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_description2, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_description2, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_description2, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_description2, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_description2, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_title2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title2, 108);
    lv_obj_set_y(ui_title2, 165);
    lv_obj_set_align(ui_title2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_title2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_title2, "title2");
    lv_obj_set_style_text_font(ui_title2, &ui_font_opensansSemiBolt21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_title2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_title2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_title2, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_title2, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_title2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_title2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_title2, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_description1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_description1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_description1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_description1, 224);
    lv_obj_set_y(ui_description1, 270);
    lv_label_set_long_mode(ui_description1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_description1, "line1");
    lv_obj_set_style_text_font(ui_description1, &ui_font_opensans182, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_description1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_description1, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_description1, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_description1, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_description1, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_description1, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title1, -77);
    lv_obj_set_y(ui_title1, 165);
    lv_obj_set_align(ui_title1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_title1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_title1, "title1");
    lv_obj_set_style_text_font(ui_title1, &ui_font_opensansSemiBolt21, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_title1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_title1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_title1, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_title1, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_title1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_title1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_title1, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar1 = lv_calendar_create(ui_Screen1);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 293);
    lv_obj_set_height(ui_Calendar1, 229);
    lv_obj_set_x(ui_Calendar1, -51);
    lv_obj_set_y(ui_Calendar1, 259);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_set_style_border_width(ui_Calendar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Calendar1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Calendar1, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hum = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_hum, &ui_img_humidity_png);
    lv_obj_set_width(ui_hum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hum, -327);
    lv_obj_set_y(ui_hum, 63);
    lv_obj_set_align(ui_hum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hum, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_hum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_hum, 300);
    lv_obj_set_style_transform_scale(ui_hum, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vis = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_vis, &ui_img_visiblity_png);
    lv_obj_set_width(ui_vis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vis, -330);
    lv_obj_set_y(ui_vis, -91);
    lv_obj_set_align(ui_vis, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vis, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_vis, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_vis, 330);
    lv_obj_set_style_transform_scale(ui_vis, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_temp1, &ui_img_temp_png);
    lv_obj_set_width(ui_temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp1, -328);
    lv_obj_set_y(ui_temp1, 114);
    lv_obj_set_align(ui_temp1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_temp1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_temp1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_temp1, 300);
    lv_obj_set_style_transform_scale(ui_temp1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wind = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_wind, &ui_img_wind_png);
    lv_obj_set_width(ui_wind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wind, -328);
    lv_obj_set_y(ui_wind, -7);
    lv_obj_set_align(ui_wind, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wind, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_wind, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -199);
    lv_obj_set_y(ui_time, 151);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00");
    lv_obj_set_style_text_font(ui_time, &ui_font_Font60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_time, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_time, 470, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 105);
    lv_obj_set_height(ui_Bar1, 2);
    lv_obj_set_x(ui_Bar1, -370);
    lv_obj_set_y(ui_Bar1, 79);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar1,
                                                                                           lv_obj_get_style_pad_right(ui_Bar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar2 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar2, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 105);
    lv_obj_set_height(ui_Bar2, 2);
    lv_obj_set_x(ui_Bar2, -370);
    lv_obj_set_y(ui_Bar2, 29);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar2,
                                                                                           lv_obj_get_style_pad_right(ui_Bar2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Bar3 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar3, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 105);
    lv_obj_set_height(ui_Bar3, 2);
    lv_obj_set_x(ui_Bar3, -370);
    lv_obj_set_y(ui_Bar3, -60);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar3,
                                                                                           lv_obj_get_style_pad_right(ui_Bar3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_description3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_description3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_description3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_description3, 93);
    lv_obj_set_y(ui_description3, 269);
    lv_label_set_long_mode(ui_description3, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_description3, "line1");
    lv_obj_set_style_text_font(ui_description3, &ui_font_opensansItalic2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_description3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_description3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_description3, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_description3, 270, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_height(ui_description3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_description3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_description3, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -2);
    lv_obj_set_y(ui_temp, 137);
    lv_obj_set_align(ui_temp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_temp, "5.21");
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_temp, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp2, 16);
    lv_obj_set_y(ui_temp2, 126);
    lv_obj_set_align(ui_temp2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_temp2, "C");
    lv_obj_set_style_text_font(ui_temp2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_temp2, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity, -2);
    lv_obj_set_y(ui_humidity, 77);
    lv_obj_set_align(ui_humidity, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_humidity, "50");
    lv_obj_set_style_text_font(ui_humidity, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_humidity, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidity1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humidity1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humidity1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humidity1, 17);
    lv_obj_set_y(ui_humidity1, 73);
    lv_obj_set_align(ui_humidity1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_humidity1, "%");
    lv_obj_set_style_text_font(ui_humidity1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_humidity1, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_windspeed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_windspeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_windspeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_windspeed, -3);
    lv_obj_set_y(ui_windspeed, 20);
    lv_obj_set_align(ui_windspeed, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_windspeed, "8.75");
    lv_obj_set_style_text_font(ui_windspeed, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_windspeed, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_windspeed1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_windspeed1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_windspeed1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_windspeed1, 16);
    lv_obj_set_y(ui_windspeed1, 23);
    lv_obj_set_align(ui_windspeed1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_windspeed1, "km/h");
    lv_obj_set_style_text_font(ui_windspeed1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_windspeed1, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_visibility = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_visibility, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_visibility, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_visibility, -3);
    lv_obj_set_y(ui_visibility, -60);
    lv_obj_set_align(ui_visibility, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_visibility, "10000");
    lv_obj_set_style_text_font(ui_visibility, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_visibility, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_visibility1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_visibility1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_visibility1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_visibility1, 13);
    lv_obj_set_y(ui_visibility1, -60);
    lv_obj_set_align(ui_visibility1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_visibility1, "meter");
    lv_obj_set_style_text_font(ui_visibility1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_visibility1, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar4, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar4, 240);
    lv_obj_set_height(ui_Bar4, 2);
    lv_obj_set_x(ui_Bar4, 88);
    lv_obj_set_y(ui_Bar4, 120);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_transform_rotation(ui_Bar4, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Bar4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Bar4,
                                                                                           lv_obj_get_style_pad_right(ui_Bar4, LV_PART_MAIN) + 1, LV_PART_MAIN);

}
